apiVersion: v1
kind: Service
metadata:
  name: sre-service
spec:
  type: LoadBalancer    # Correct capitalization
  selector:
    app: sre
  ports:
  - protocol: TCP
    port: 80       # Service port
    targetPort: 8080  # Container port
    nodePort: 30080

